<?php

/**
 * @file
 * Contains general functionality of the module.
 */

/**
 * Implements hook_help().
 */
function math_captcha_help($path, $arg) {
  switch ($path) {
    case 'admin/config/people/captcha/math_captcha':
      return '<p>' . t('Provide math CAPTCHAs like \'two + three = ?\' and \'2 times ? = 6\'.') . '</p>';
  }
}

/**
 * Implements hook_captcha().
 */
function math_captcha_captcha($op, $captcha_type = '') {
  switch ($op) {
    case 'list':
      return ['Math CAPTCHA'];

    case 'generate':
      if ($captcha_type == 'Math CAPTCHA') {
        require_once('math_captcha.challenge.inc');
        // Get the available challenges
        $enabled_challenges = _math_captcha_enabled_challenges();
        $challenges = array_filter($enabled_challenges);
        $challenge = $challenges[array_rand($challenges)];
        $form_item = call_user_func("_math_captcha_{$challenge}_challenge");
        return $form_item;
      }
      break;
  }
}

/**
 * Function for getting the enabled challenges (e.g. for use as checkboxes default_value)
 */
function _math_captcha_enabled_challenges() {
  $enabled = variable_get('math_captcha_enabled_challenges', [
    'addition' => 'addition',
    'subtraction' => 'subtraction',
    'multiplication' => 'multiplication'
  ]);
  
  return $enabled;
}

// /**
//  * Process the response to the Math CAPTCHA before validation.
//  */
// function math_captcha_process($element, $edit) {
//   if (\Drupal::config('math_captcha.settings')->get('math_captcha_ignore_spaces')) {
//     $element['#value'] = preg_replace('/\s*/', '', $element['#value']);
//   }
//   return $element;
// }
