<?php
// $Id$

DEFINE(CSS_CAPTCHA_ALLOWED_CHARACTERS, 'aAbBcCdDeEfFgGhHijkKLmMnNpPqQrRsStTuUvVwWxXyYzZ123456789');

/**
 * Implementation of hook_menu().
 */
function css_captcha_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'admin/user/captcha/css_captcha',
      'title' => t('CSS captcha'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('css_captcha_settings_form'),
      'type' => MENU_LOCAL_TASK,
    );
  }
  return $items;
}

/**
 * Function for the settings form
 */
function css_captcha_settings_form() {
  $form = array();
  $form['css_captcha_allowed_characters'] = array(
    '#type' => 'textfield',
    '#title' => t('Characters to use in the code'),
    '#default_value' => variable_get('css_captcha_allowed_characters', CSS_CAPTCHA_ALLOWED_CHARACTERS),
  );
  $form['css_captcha_code_length'] = array(
    '#type' => 'select',
    '#title' => t('Code length'),
    '#options' => array(4=>4, 5=>5, 6=>6, 7=>7, 8=>8),
    '#default_value' => (int) variable_get('css_captcha_code_length', 4),
  );
  return system_settings_form($form);
}

/**
 * Validation function
 */
function css_captcha_settings_form_validate($form_id, $form_values) {
  if ($form_id == 'css_captcha_settings_form') {
    if (preg_match('/\s/', $form_values['css_captcha_allowed_characters'])) {
      form_set_error('css_captcha_allowed_characters', t('The list of characters to use should not containt spaces.'));
    }
  }
}

function css_captcha_captcha($op, $captcha_type='', $response='') {
  switch($op) {
    case 'list':
      return array("CSS captcha");
    case 'generate':
      if ($captcha_type == "CSS captcha") {
        // get settings
        $allowed_chars = _text_captcha_utf8_split(variable_get('css_captcha_allowed_characters', CSS_CAPTCHA_ALLOWED_CHARACTERS));
        $code_length = (int) variable_get('css_captcha_code_length', 4);
        // build solution and $code_struct
        $solution = '';
        $code_struct = array();
        for ($i = 0; $i < $code_length; $i++) {
          $character = $allowed_chars[array_rand($allowed_chars)];
          $code_struct[$i] = array('content' => $character, 'size' => 1);
          $solution .= $character;
        }
        // generate css scrambling
        $c = 0;
        while (count($code_struct) > 1) {
          // pick random neighbouring items from $code_struct
          $i = mt_rand(0, count($code_struct) - 2);
          $item_left = $code_struct[$i];
          $item_right = $code_struct[$i+1];
          // merge
          $merged_size = $item_left['size']+$item_right['size'];
          if (mt_rand(0,1)) {
            // normal merge: $item_left first $item_right second
            $merged_content = "<div style=\"width:{$item_left['size']}em;float:left;\">{$item_left['content']}</div>"
              . "<div style=\"width:{$item_right['size']}em;float:left;\">{$item_right['content']}</div>";
          }
          else {
            // mirror merge: $item_right first $item_left second
            $merged_content = "<div style=\"width:{$item_right['size']}em;float:right;\">{$item_right['content']}</div>"
              . "<div style=\"width:{$item_left['size']}em;float:left;\">{$item_left['content']}</div>";
          }
          $item = array(
            'content' => "<div style=\"width:{$merged_size}em;height:1.5em;\">$merged_content</div>",
            'size' => $merged_size,
          );
          array_splice($code_struct, $i, 2, array($item));
          // make array indices contiguous again
          $code_struct = array_values($code_struct);
        }
        // build captcha challenge
        $captcha = array();
        $captcha['solution'] = $solution;
        $captcha['form']['captcha_response'] = array (
          '#type' => 'textfield',
          '#title' => t('Enter the code above'),
          '#size' => 10,
          '#prefix' => $code_struct[0]['content'],
          '#maxlength' => 10,
          '#required' => TRUE,
          '#description' => t('Enter the code without spaces and pay attention to upper/lower case.')
        );
        $captcha['preprocess'] = FALSE;
        return $captcha;
      }
    break;
  }
}
