<?php
// $Id$

/**
 * Implementation of a "meta captcha" which randomly switches between several captcha types
 */


/**
 * Implementation of hook_help().
 */
function random_captcha_type_help($section) {
  switch ($section) {
    case 'admin/user/captcha/random_captcha_type':
      return '<p>'. t('This captcha could be seen as a "meta captcha type", which randomly picks one of the selected captcha types.') .'</p>';
  }
  return $output;
}

/**
 * Implementation of hook_menu().
 */
function random_captcha_type_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    // add an administration tab for random_captcha_type
    $items[] = array(
      'path' => 'admin/user/captcha/random_captcha_type',
      'title' => t('Random captcha type'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('random_captcha_type_settings_form'),
      'type' => MENU_LOCAL_TASK,
    );
  }
  return $items;
}

/**
 * Function for getting all the possible captcha challenges to switch between.
 * For use as #options entry of a checkboxes widget.
 */
function _random_captcha_type_get_all_challenges() {
  $captcha_challenges = array();
  foreach (module_implements('captcha') as $module) {
    // skip random_captcha_type module
    if ($module == 'random_captcha_type') {
      continue;
    }
    // get available  challenges
    $result = call_user_func_array($module .'_captcha', 'list');
    if (is_array($result)) {
      foreach ($result as $challenge) {
        $captcha_challenges["$module/$challenge"] = "$challenge ($module)";
      }
    }
  }
  return $captcha_challenges;
}

/**
 * Function for getting the enabled captcha challenges.
 * Alternative of variable_get('random_captcha_type_challenges', ...) with
 * sensible default value.
 * For use as #default_value of checkboxes widget.
 * Returns an array mapping "$module/$challenge" to "$module/$challenge" if
 * that challenge is enabled or 0 if not enabled.
 */
function _random_captcha_type_get_enabled_challenges() {
  $enabled_challenges = variable_get('random_captcha_type_challenges', array());
  if (!$enabled_challenges) {
    $keys = array_keys(_random_captcha_type_get_all_challenges());
    $enabled_challenges = array_combine($keys, $keys);
    variable_set('random_captcha_type_challenges', $enabled_challenges);
  }
  return $enabled_challenges;
}

/**
 * Configuration form
 */
function random_captcha_type_settings_form() {

  if (count(array_filter(_random_captcha_type_get_enabled_challenges())) < 2) {
    drupal_set_message(t('You need at least two captcha challenge types (other than %random_captcha_type).', array('%random_captcha_type' => 'Random captcha type')), 'error');
  }
  $form = array();
  $captcha_challenges = _random_captcha_type_get_all_challenges();
  $form['random_captcha_type_challenges'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Randomly switch between'),
    '#options' => $captcha_challenges,
    '#default_value' => _random_captcha_type_get_enabled_challenges(),
  );
  return system_settings_form($form);
}

/**
 * Implementation of form validation
 */
function random_captcha_type_settings_form_validate($form_id, $form_values) {
  if ($form_id == 'random_captcha_type_settings_form') {
    // at least 2 captcha types should be selected
    if (count(array_filter($form_values['random_captcha_type_challenges'])) < 2) {
      form_set_error('random_captcha_type_challenges', t('You should select at least two captcha types.'));
    }
  }
}

/**
 * Implementation of hook_captcha
 */
function random_captcha_type_captcha($op, $captcha_type='') {
  switch ($op) {
    case 'list':
      return array('Random captcha type');
    case 'generate':
      if ($captcha_type == 'Random captcha type') {
        $challenges = array_filter(_random_captcha_type_get_enabled_challenges());
        $key = array_rand($challenges);
        list($module, $type) = explode('/', $challenges[$key]);
        return module_invoke($module, 'captcha', 'generate', $type);
      }
  }
}
