<?php

/**
 * @file
 * Contains general functionality of the module.
 */

/**
 * Function to get a list of available fonts.
 *
 * @TODO: Rebuild loading fonts with plugins.
 *
 * @return array
 */
function _ascii_art_captcha_available_fonts() {
  $available_fonts = [];
  $fontsdirectory = drupal_get_path('module', 'ascii_art_captcha') . '/fonts';
  $pattern = '/ascii_art_captcha_font_([a-zA-Z0-9]+)\.[iI][nN][cC]$/';
  $directory_files = file_scan_directory($fontsdirectory, $pattern);
  foreach ($directory_files as $font) {
    $regs = [];
    preg_match($pattern, $font->filename, $regs);
    $available_fonts[$regs[1]] = $regs[1];
  }
  asort($available_fonts);
  return $available_fonts;
}
